#!/usr/bin/env bash
set -euo pipefail

# Generated by dcli-bootc gen — edit modules/*.yaml instead
# Profile: dcli-image

# === flatpak remotes ===
flatpak remote-add --if-not-exists --system flathub "https://dl.flathub.org/repo/flathub.flatpakrepo"

# === base: Base system packages and configuration ===
dnf5 -y copr enable theblackdon/dcli-bootc
dnf5 -y copr enable stenstorp/brlaser

dnf install -y \
    tmux \
    dcli-bootc \
    printer-driver-brlaser

# Copy files/ tree into image
rsync -rlptD /ctx/files/ /
systemctl enable bootc-fetch-apply-updates.timer

# === cleanup ===
dnf clean all && rm -rf /var/cache/dnf/*
